
-- alter table product add column brand text;
update product set brand=regexp_replace(product_type, '^.*\\', '');
update product set brand ='NA ' ||brand where brand in ('啤酒', '面饼', '其他', '期初类', '礼盒及包装袋', '红酒' , '芝士乳酪' , '采购费用类', '销售费用类', '非食品');
update product set brand ='TABASCO' where name like '%TABASCO%';
update product set brand ='丽尔泰' where name like '%丽尔泰%';
update product set brand ='丽米' where name like '%丽米牌%';
update product set brand ='乐事' where name like '%乐事%';
update product set brand ='乐家' where name like '%乐家%';
update product set brand ='亨氏' where name like '%亨氏牌%';
update product set brand ='优实' where name like '%优实%';
update product set brand ='伦巴第' where name like '%伦巴第%';
update product set brand ='伯瑞' where name like '%伯瑞%';
update product set brand ='佳乐' where name like '%佳乐%';
update product set brand ='卡夫' where name like '%卡夫牌%';
update product set brand ='卡萨诺瓦' where name like '%卡萨诺瓦%';
update product set brand ='友加' where name like '%友加%';
update product set brand ='古雅' where name like '%古雅%';
update product set brand ='和情缤咖时' where name like '%和情缤咖时%';
update product set brand ='四季宝' where name like '%四季宝%';
update product set brand ='圣丹尼斯' where name like '%圣丹尼斯%';
update product set brand ='坎通纳大师巴贝拉' where name like '%坎通纳大师巴贝拉%';
update product set brand ='塔乌丝' where name like '%塔乌丝%';
update product set brand ='天娜' where name like '%天娜%';
update product set brand ='奇泰瑞' where name like '%奇泰瑞%';
update product set brand ='好乐门' where name like '%好乐门%';
update product set brand ='安拉' where name like '%安拉%';
update product set brand ='家乐' where name like '%家乐牌%';
update product set brand ='小胖子' where name like '%小胖子%';
update product set brand ='屋仔' where name like '%屋仔%';
update product set brand ='康莱纳' where name like '%康莱纳%';
update product set brand ='戴茜' where name like '%戴茜%';
update product set brand ='柏札莱' where name like '%柏札莱%';
update product set brand ='桂格老人' where name like '%桂格老人%';
update product set brand ='海中厨' where name like '%海中厨%';
update product set brand ='滋米' where name like '%滋米牌%';
update product set brand ='潘泰' where name like '%潘泰%';
update product set brand ='牛斗' where name like '%牛斗%';
update product set brand ='特兰丁' where name like '%特兰丁%';
update product set brand ='琦雷萨' where name like '%琦雷萨牌%';
update product set brand ='百利' where name like '%百利牌%';
update product set brand ='百味来' where name like '%百味来%';
update product set brand ='皇冠' where name like '%皇冠%';
update product set brand ='立顿牌' where name like '%立顿牌%';
update product set brand ='索浓' where name like '%索浓%';
update product set brand ='维鲜' where name like '%维鲜%';
update product set brand ='罗兰' where name like '%罗兰%';
update product set brand ='罗玛' where name like '%罗玛%';
update product set brand ='罗菲儿美乐' where name like '%罗菲儿美乐%';
update product set brand ='美国碧根' where name like '%美国碧根%';
update product set brand ='美极' where name like '%美极%';
update product set brand ='翁布里亚大师' where name like '%翁布里亚大师%';
update product set brand ='旗牌' where name like '%旗牌%';
update product set brand ='老船长' where name like '%老船长%';
update product set brand ='能多益' where name like '%能多益%';
update product set brand ='芭比奥维托' where name like '%芭比奥维托%';
update product set brand ='英雄' where name like '%英雄%';
update product set brand ='萨哈萨拉' where name like '%萨哈萨拉%';
update product set brand ='蜜月金' where name like '%蜜月金%';
update product set brand ='西施佳雅' where name like '%西施佳雅%';
update product set brand ='西米公爵' where name like '%西米公爵%';
update product set brand ='西米' where name like '%西米%' and name not like '%西米公爵%';
update product set brand ='贝蒂妙厨' where name like '%贝蒂妙厨牌%';
update product set brand ='贵族巴贝拉阿斯蒂' where name like '%贵族巴贝拉阿斯蒂%';
update product set brand ='金凯利' where name like '%金凯利%';
update product set brand ='阿尔卑' where name like '%阿尔卑%';
update product set brand ='鱿鱼标' where name like '%鱿鱼标%';
update product set brand ='鹰牌' where name like '%鹰牌%';

-- alter  table product add column generic_name text;

update product set generic_name= regexp_replace(name, '^.*'||brand||'牌*', '');
update product set generic_name= regexp_replace(generic_name, '^.*℃', '');
update product set generic_name= regexp_replace(generic_name, '[ (]*[0-9].*$', '') where brand not like 'NA%' and  generic_name !~ '^[0-9]';

--alter table product add column product_name text;
update product set product_name = regexp_replace(name, '^.*℃', '');

alter table product add column category varchar(1);
update product set category='P';
update product set category='D' where (generic_name like '%奶%' or generic_name like '%水%') and not (generic_name like '%奶酪%' or generic_name like '%奶油%' or generic_name like '%水杯%' or generic_name like '%水牛%' );
update product set category='P' where category = 'D' and generic_name in ('B级速冻水果(树莓/国产)500g', '大罐盐水浸亚之竹芯(朝鲜蓟)');

update product set category='U' where brand like'NA%' or brand in ('3M', '沙伯特');
update product set category='A' where category='P' and (generic_name  like '%酒%' or generic_name like '%干红%' ) and  generic_name not like '%酒醋%' ;
update product set category='U' where category='P' and generic_name like '%礼盒外箱%';

alter table product add column category_code text;
update product set category_code=null ;
update product set category_code='NA' where '一般商品\非食品' =product_type;
update product set category_code='NA' where  '一般商品\礼盒及包装袋'= product_type;
update product set category_code='NA' where brand='沙伯特';
update product set category_code='NA' where brand='3M';
update product set category_code='15.1'  	where category_code is null and brand='品客';
update product set category_code='02.1.2' 	where category_code is null and brand='拉图'  and product_name !~ '(ABC)';
update product set category_code='02.1.2' 	where category_code is null and brand='乐家' and product_name ~ '(油)' and product_name !~ '(外箱)';
update product set category_code='06.4.2' 	where category_code is null and brand='阿布素' and product_name !~ '(酱)';
update product set category_code='12.3'  	where category_code is null and brand='乐家' and product_name ~ '(醋)' and product_name !~ '(ABC)' ;
update product set category_code='14.2.4'  	where category_code is null and product_name ~ '(干红|葡萄酒)' and product_name !~ '(杯|醋)' ;
update product set category_code='14.2.6.1' 	where category_code is null and product_name like  '%啤酒%';
update product set category_code='14.2.3.3' 	where category_code is null and product_name like  '%马莎拉酒%';
update product set category_code='12.3' 	where category_code is null and product_name ~ '(香醋|酒醋|黑醋|白醋|苹果醋)' and product_name !~ '(果酱)';
update product set category_code='01.6' 	where category_code is null and product_name ~ '(奶酪)' and product_name !~ '(云吞|饺|酱|糕|味)';
update product set category_code='01.1.1.1' 	where category_code is null and product_name ~ '(牛奶)' and product_name !~ '(粉)';
update product set category_code='01.7' 	where category_code is null and product_name ~ '(酸奶)';
update product set category_code='02.1.2' 	where category_code is null and product_name ~ '(橄榄油)' and product_name !~'(浸)';
update product set category_code='06.4.2'  	where category_code is null and product_name ~ '(通心粉|意大利面|意面)' and product_name !~'(酱|勺)';
update product set category_code='12.6.2'  	where category_code is null and product_name ~ '(调味酱|沾酱)';
update product set category_code='12.6.2'   	where category_code is null and product_name ~ '(芝麻酱)'  and product_name !~ '(ABC)';
update product set category_code='12.6.2'  	where category_code is null and product_name ~ '(意大利面酱)' ;
update product set category_code='02.2.1.1'   	where category_code is null and product_name ~ '(淡奶油)';
update product set category_code='02.1.2'  	where category_code is null and product_name ~ '(籽油|粟米油)' and  product_name !~ '(浸)';
update product set category_code='01.1.1.1'  	where category_code is null and product_name ~ '(金奶|脱脂奶|全脂淡奶)';
update product set category_code='15.1'  	where category_code is null and product_name ~ '(玉米脆)' ;
update product set category_code='06.4.2'  	where category_code is null and product_name ~ '(意大利.*面)' ;
update product set category_code='06.4.2' 	where category_code is null and product_name ~ '(酱面|拉面)'  and product_name !~ '(ABC)';
update product set category_code='01.6'  	where category_code is null and product_name ~ '(芝士|干酪)'  and product_name !~ '(糕)';
update product set category_code='15.1'  	where category_code is null and product_name ~ '(饼干)';
update product set category_code='08.2.1.2'  	where category_code is null and product_name ~ '(火腿)' and product_name !~ '(ABC)';                      
update product set category_code='04.2.2'  	where category_code is null and product_name ~ '(番茄|玉米粒)'  and product_name !~ '(饼|酱|沙司|味)';
update product set category_code='14.1.1.1'  	where category_code is null and product_name ~ '(泉水)'  and product_name !~ '(ABC)';
update product set category_code='07.1.3'   	where category_code is null and product_name ~ '(煎饼|烙饼)'  and product_name !~ '(ABC)';
update product set category_code='15.2' 	where category_code is null and product_name ~ '(桃仁)'  and product_name !~ '(饼)';
update product set category_code='06.5' 	where category_code is null and product_name ~ '(汤圆)'  and product_name !~ '(ABC)';  
update product set category_code='04.2.2.6'  	where category_code is null and product_name ~ '(豆)'  and product_name !~ '(糕|饺|土)';
update product set category_code='16.0'  	where category_code is null and product_name ~ '(烧卖|虾饺)'  and product_name !~ '(ABC)';
update product set category_code='12.6.2'  	where category_code is null and product_name ~ '(酱)'  and product_name !~ '(拉面|酱面)';
update product set category_code='12.5.1' 	where category_code is null and product_name ~ '(汤)'  and product_name !~ '(ABC)';
update product set category_code='15.3'  	where category_code is null and product_name ~ '(鱼柳)' and  product_name !~ '(ABC)'; 
update product set category_code='01.6'  	where category_code is null and product_name ~ '(高达奶酪)' and  product_name !~ '(ABC)';
update product set category_code='01.3.1'  	where category_code is null and product_name ~ '(炼奶)' and  product_name !~ '(ABC)';
update product set category_code='07.1.3'  	where category_code is null and product_name ~ '(卷饼)'  and product_name !~ '(ABC)';
update product set category_code='11.2'  	where category_code is null and product_name ~ '(糖浆)'  and product_name !~ '(ABC)';
update product set category_code='06.4.2'  	where category_code is null and product_name ~ '(杜兰小麦)'  and product_name !~ '(ABC)';
update product set category_code='14.1.4.3'  	where category_code is null and product_name ~ '(热巧克力粉)'  and product_name !~ '(ABC)';            
update product set category_code='02.2.1.1'  	where category_code is null and product_name ~ '(黄油)'  and product_name !~ '(ABC)';
update product set category_code='02.1.2'  	where category_code is null and product_name ~ '(调.*油)'  and product_name !~ '(ABC)';
update product set category_code='02.1.2'   	where category_code is null and product_name ~ '(油)'  and product_name !~ '(浸|奶)'
update product set category_code='06.4.2'   	where category_code is null and product_name ~ '(意粉)'  and product_name !~ '(ABC)'; 
update product set category_code='16.0'   	where category_code is null and product_name ~ '(云吞|饺)'  and product_name !~ '(ABC)';
update product set category_code='01.6' 	where category_code is null and product_name ~ '(奶酪)'  and product_name !~ '(蛋糕)';
update product set category_code='15.1' 	where category_code is null and product_name ~ '(玉米片)'  and product_name !~ '(ABC)';
update product set category_code='07.1.3' 	where category_code is null and product_name ~ '(薄饼|披萨饼)'  and product_name !~ '(ABC)';
update product set category_code='07.1.3' 	where category_code is null and product_name ~ '(黄玉米饼)' and product_name !~ '(ABC)';
update product set category_code='15.2' 	where category_code is null and product_name ~ '(饼)' and product_name !~ '(ABC)';
update product set category_code='07.1.1' 	where category_code is null and product_name ~ '(面包棍)' and product_name !~ '(ABC)';                     
update product set category_code='07.2.1' 	where category_code is null and product_name ~ '(蛋糕)' and product_name !~ '(纸袋)';                      
update product set category_code='NA' 		where category_code is null and product_name ~ '(碟|叉|杯|电镀|勺|彩色|羹)'  and product_name !~ '(ABC)'; 
update product set category_code='05.2' 	where category_code is null and product_name ~ '(星星糖)'  and product_name !~ '(ABC)';
update product set category_code='06.4.2' 	where category_code is null and product_name ~ '(通粉)'  and product_name !~ '(ABC)';                      
update product set category_code='14.1.5' 	where category_code is null and product_name ~ '(茶)'  and product_name !~ '(ABC)';  
update product set category_code='01.6' 	where category_code is null and product_name ~ '(马苏里拉)'   and product_name !~ '(ABC)'; 
update product set category_code='06.4.2' 	where category_code is null and product_name ~ '(蛋面)'   and product_name !~ '(ABC)';
update product set category_code='15.1' 	where category_code is null and product_name ~ '(粟米片)'   and product_name !~ '(ABC)';
update product set category_code='NA' 		where category_code is null and product_type = '一般商品\麦西恩';

alter table product add column unit_size text;
update product set unit_size = substring(package_spec, '\*(.+)$');
update product set unit_size =substring(package_spec, '(.+)\/.+$') where unit_size is null and substring(package_spec, '\/(.+)$')= measure_unit;
update product set unit_size = substring(package_spec, '-(.+)$') where unit_size is null; 
update product set unit_size = package_spec where unit_size is null and package_spec like '%g'; 
